name: Build and Test Na.Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-windows-x64:
    runs-on: windows-latest
    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x # Or your .NET version
    - name: Display .NET Info
      run: dotnet --info
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Change directory to src
      run: cd src
    - name: Restore dependencies
      run: dotnet restore
    - name: Build (Debug)
      run: dotnet build --configuration Debug --no-restore
    - name: Test (Debug)
      run: dotnet test --configuration Debug --no-restore --verbosity normal
    - name: Build (Release)
      run: dotnet build --configuration Release --no-restore
    - name: Test (Release)
      run: dotnet test --configuration Release --no-restore --verbosity normal
