name: Build and Test Na.Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-windows-x64:
    runs-on: windows-latest
    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x # Or your .NET version
    - name: Display .NET Info
      run: dotnet --info
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Display current directory
      run: pwd
    - name: Restore dependencies
      run: dotnet restore .\src\Na.Core.sln
    - name: Build (Debug)
      run: dotnet build .\src\Na.Core.sln --configuration Debug --no-restore
    - name: Test (Debug)
      run: dotnet test .\src\Na.Core.sln --configuration Debug --no-restore --verbosity normal
    - name: Build (Release)
      run: dotnet build .\src\Na.Core.sln --configuration Release --no-restore
    - name: Test (Release)
      run: dotnet test .\src\Na.Core.sln --configuration Release --no-restore --verbosity normal
